### ISSUE TITLE
这个应用没有申请特殊权限就可以实现

### ISSUE THREAD

**Issue by chenyue404** [haruue/PeekIntent#1]
https://play.google.com/store/apps/details?id=co.easy4u.ncleaner
最近也在弄这方面的东西，找到这个应用，没有申请什么特殊权限就可以在7.0以上的手机拿到Intent，反编译之后也没有找到什么特殊的地方，也是反射拿取。
希望可以研究一下。

**Comment by haruue** [comment]
Anyway the `co.easy4u.ncleaner` use nothing about the `ActivityManagerNative.getDefault() .getIntentForIntentSender(pendingIntent.mTarget);`, so it won't require root permission. 

In fact the mainly problem is how to get the wrapped intent in the `PendingIntent`, we did it by this hidden API because we want to construct those intents in another app (see README). However, if you have a `PendingIntent`, and you just want to start its intent, the [`PendingIntent.send()`](https://developer.android.com/reference/android/app/PendingIntent.html#send()) will be the easiest way. 

With the [`NotificationListenerService`](https://developer.android.com/reference/android/service/notification/NotificationListenerService), you can do a lot thing as well, such as snooze a notification for a long time, and the actually behavior just like to ban them. 

And if you have any question about implementation of other application, you can send a email to its developer, rather than open a issue here. Usually they will tell you the answer if you make a donation to them, it may be a easier way to get what you want.

**Comment by chenyue404** [comment]
Thanks
